% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Statistical Analysis of Chronodel Test},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Statistical Analysis of Chronodel Test}
\author{}
\date{\vspace{-2.5em}2026-04-09}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{Chronodel Data Analysis}\label{chronodel-data-analysis}

The project that I am working on is to analyze the data of the
\textbf{\emph{Chronodel test}}, which is a test that measures the
ability to perform a task in a duration of 30 seconds. The data is
collected from a sample of participants who have taken the test (n =
43). The goal of this analysis is to experiment the test Chronodel
understand the distribution of the results and to compare the results of
the Chronodel test with other tests that measure similar abilities, by
others, i mean, Day Of the Week Backward and (\emph{DOTWB}) and Month Of
The Year Backward (\emph{MOTYB}).

At the beginning of the analysis, we wanted to calculate the
\textbf{sensibility}, \textbf{specificity}, \textbf{positive predictive}
value and \textbf{negative predictive value} of the Chronodel test, but
at the reception of the results, we observed low variability in the
results of the Chronodel test, which is really low, and that the
majority of the patients have a result of 1 on the Chronodel test, which
means that they succeed the test, because we expected to have a more
variability in the results, and also because we expected to have a lower
success rate for the Chronodel test, so we decided to change our
analysis plan and to focus on pourcentage of success for the three tests
(\emph{DOTWB}, \emph{MOTYB}, \emph{Chronodel}) to evaluate the coherence
between the results and at the end, the distribution of the results for
the three tests, to evaluate the variability and the ceiling effect.

A small number of missing values were observed across variables. As
these were limited and not overlapping across tests, analyses were
conducted using available data, with missing values excluded where
necessary.

\section{inclusion of the data}\label{inclusion-of-the-data}

The data cleaning data has been made earlier, in visual studio code, and
the data is \textbf{ready to be analyzed}, so we will start by loading
the data in Rstudio.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"Stat\_Chronodel\_Rstudio\_test.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\section{Total subjects}\label{total-subjects}

To do the kappa test, we need to have complete cases for the variables
``jour\_reussite'' and ``mois\_reussi'', so we will check how many
complete cases we have for these two variables.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{complete.cases}\NormalTok{(Data[, }\FunctionTok{c}\NormalTok{(}\StringTok{"jour\_reussite"}\NormalTok{, }\StringTok{"mois\_reussi"}\NormalTok{)]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 36
\end{verbatim}

We have a total of \textbf{36 completes cases} for these two variables,
which is enough to do the Kappa test.

\section{Kappa test}\label{kappa-test}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(irr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Le chargement a nécessité le package : lpSolve
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kappa2}\NormalTok{(Data[, }\FunctionTok{c}\NormalTok{(}\StringTok{"jour\_reussite"}\NormalTok{, }\StringTok{"mois\_reussi"}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Cohen's Kappa for 2 Raters (Weights: unweighted)
## 
##  Subjects = 36 
##    Raters = 2 
##     Kappa = 0.0859 
## 
##         z = 1.27 
##   p-value = 0.204
\end{verbatim}

\subsection{Kappa test results}\label{kappa-test-results}

As result of the Kappa test, we have a \textbf{kappa value} of
\textbf{0.0859}, which is a really low value of agreement between the
\emph{DOTWB} and \emph{MOTYB} tests. This suggest that the observed
agreement is only slightly above what would be expected by chance. This
low Kappa value is likely explained by the highly unbalanced
distribution of the data, with a majority of successful outcomes in the
day-based test (ceiling effect), as well as the presence of discordant
cases.

The p-value associated with the Kappa statistic was \textbf{0.204},
which is above the conventional significance threshold of \textbf{0.05}.
Therefore, we fail to reject the null hypothesis (H0: κ = 0), meaning
that there is no statistically significant agreement beyond chance
between the two tests.''

\section{Cross table}\label{cross-table}

We will create a cross table to estimate the coherence between the
results of the two tests (\emph{DOTWB} and \emph{MOTYB}).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{jour\_reussite, Data}\SpecialCharTok{$}\NormalTok{mois\_reussi, }\AttributeTok{useNA =} \StringTok{"no"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    
##      0  1
##   0  1  0
##   1 13 22
\end{verbatim}

\subsection{DOTWB vs MOTYB
Concordance}\label{dotwb-vs-motyb-concordance}

From the cross table, we observe:

\begin{itemize}
\tightlist
\item
  1 subject failed both \emph{DOTWB} and \emph{MOTYB}\\
\item
  0 subjects failed \emph{DOTWB} but succeeded \emph{MOTYB}
\item
  13 subjects succeeded \emph{DOTWB} but failed \emph{MOTYB}
\item
  22 subjects succeeded both tests
\end{itemize}

This results in 63.9\% concordance (22+1/36) and \textbf{36.1\%
discordance} (13/36), explaining the low Kappa value.

\section{success rate}\label{success-rate}

We will do now, the analysis of the success rate for the three tests, to
evaluate the coherence between the results of the three tests, and to
evaluate the ceiling effect for each test.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{taux\_jour }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{jour\_reussite, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{taux\_mois }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{mois\_reussi, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{taux\_chrono }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{chrono\_reussi, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{taux }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(taux\_jour, taux\_mois, taux\_chrono)}

\FunctionTok{barplot}\NormalTok{(taux,}
        \AttributeTok{names.arg =} \FunctionTok{c}\NormalTok{(}\StringTok{"DOTWB"}\NormalTok{, }\StringTok{"MOTYB"}\NormalTok{, }\StringTok{"Chronodel"}\NormalTok{),}
        \AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{1.1}\NormalTok{),}
        \AttributeTok{ylab =}\NormalTok{ (}\StringTok{"success rate"}\NormalTok{),}
        \AttributeTok{main =}\NormalTok{ (}\StringTok{"success rate for the three tests"}\NormalTok{),}
        \AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{, }\StringTok{"blue"}\NormalTok{, }\StringTok{"green"}\NormalTok{))}
\FunctionTok{text}\NormalTok{(}\AttributeTok{x=}\DecValTok{1}\NormalTok{, }\AttributeTok{y=}\NormalTok{taux\_jour}\FloatTok{+0.05}\NormalTok{, }\AttributeTok{labels=}\FunctionTok{paste0}\NormalTok{(}\FunctionTok{round}\NormalTok{(taux\_jour}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\DecValTok{2}\NormalTok{), }\StringTok{"\%"}\NormalTok{))}
\FunctionTok{text}\NormalTok{(}\AttributeTok{x=}\DecValTok{2}\NormalTok{, }\AttributeTok{y=}\NormalTok{taux\_mois}\FloatTok{+0.05}\NormalTok{, }\AttributeTok{labels=}\FunctionTok{paste0}\NormalTok{(}\FunctionTok{round}\NormalTok{(taux\_mois}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\DecValTok{2}\NormalTok{), }\StringTok{"\%"}\NormalTok{))}
\FunctionTok{text}\NormalTok{(}\AttributeTok{x=}\DecValTok{3}\NormalTok{, }\AttributeTok{y=}\NormalTok{taux\_chrono}\FloatTok{+0.05}\NormalTok{, }\AttributeTok{labels=}\FunctionTok{paste0}\NormalTok{(}\FunctionTok{round}\NormalTok{(taux\_chrono}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\DecValTok{2}\NormalTok{), }\StringTok{"\%"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Stats-Chronodel-Rstudio_files/Stats-Chronodel-Rstudio_files/figure-latex/unnamed-chunk-5-1.pdf}}

For the result of the three tests, we have a success rate of 97.3\% for
the \emph{DOTWB} test, which is really high, and might suggest a ceiling
effect, we have a success rate of 58.97\% for the \emph{MOTYB} test,
which is more balanced, and that doesn't suggest a ceiling effect, and
at the end, we have a success rate of 100\% for the \emph{Chronodel}
test, which is really high, and that too as well a ceiling effect.

\section{Distribution}\label{distribution}

For the final graph, we will plot the distribution of the results for
the three tests, to evaluate the variability and the ceiling effect for
each test.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{))}
\FunctionTok{barplot}\NormalTok{(}\FunctionTok{table}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{jour\_reussite, }\AttributeTok{useNA =} \StringTok{"no"}\NormalTok{)}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(Data),}
        \AttributeTok{main=}\StringTok{"Distribution DOTWB"}\NormalTok{, }\AttributeTok{ylim=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{1.1}\NormalTok{), }\AttributeTok{col=}\FunctionTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{, }\StringTok{"green"}\NormalTok{), }\AttributeTok{names.arg =} \FunctionTok{c}\NormalTok{(}\StringTok{"0"}\NormalTok{, }\StringTok{"1"}\NormalTok{))}
\FunctionTok{text}\NormalTok{(}\AttributeTok{x=}\DecValTok{1}\NormalTok{, }\AttributeTok{y=}\FunctionTok{table}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{jour\_reussite, }\AttributeTok{useNA =} \StringTok{"no"}\NormalTok{)[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(Data)}\SpecialCharTok{+}\FloatTok{0.05}\NormalTok{, }\AttributeTok{labels=}\FunctionTok{paste0}\NormalTok{(}\FunctionTok{round}\NormalTok{(}\FunctionTok{table}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{jour\_reussite, }\AttributeTok{useNA =} \StringTok{"no"}\NormalTok{)[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(Data)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\DecValTok{2}\NormalTok{), }\StringTok{"\%"}\NormalTok{))}
\FunctionTok{text}\NormalTok{(}\AttributeTok{x=}\DecValTok{2}\NormalTok{, }\AttributeTok{y=}\FunctionTok{table}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{jour\_reussite, }\AttributeTok{useNA =} \StringTok{"no"}\NormalTok{)[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(Data)}\SpecialCharTok{+}\FloatTok{0.05}\NormalTok{, }\AttributeTok{labels=}\FunctionTok{paste0}\NormalTok{(}\FunctionTok{round}\NormalTok{(}\FunctionTok{table}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{jour\_reussite, }\AttributeTok{useNA =} \StringTok{"no"}\NormalTok{)[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(Data)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\DecValTok{2}\NormalTok{), }\StringTok{"\%"}\NormalTok{))}
\FunctionTok{barplot}\NormalTok{(}\FunctionTok{table}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{mois\_reussi, }\AttributeTok{useNA =} \StringTok{"no"}\NormalTok{)}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(Data),}
        \AttributeTok{main=}\StringTok{"Distribution MOTYB"}\NormalTok{, }\AttributeTok{ylim=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{1.1}\NormalTok{), }\AttributeTok{col=}\FunctionTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{, }\StringTok{"green"}\NormalTok{), }\AttributeTok{names.arg =} \FunctionTok{c}\NormalTok{(}\StringTok{"0"}\NormalTok{, }\StringTok{"1"}\NormalTok{))}
\FunctionTok{text}\NormalTok{(}\AttributeTok{x=}\DecValTok{1}\NormalTok{, }\AttributeTok{y=}\FunctionTok{table}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{mois\_reussi, }\AttributeTok{useNA =} \StringTok{"no"}\NormalTok{)[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(Data)}\SpecialCharTok{+}\FloatTok{0.05}\NormalTok{, }\AttributeTok{labels=}\FunctionTok{paste0}\NormalTok{(}\FunctionTok{round}\NormalTok{(}\FunctionTok{table}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{mois\_reussi, }\AttributeTok{useNA =} \StringTok{"no"}\NormalTok{)[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(Data)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\DecValTok{2}\NormalTok{), }\StringTok{"\%"}\NormalTok{))}
\FunctionTok{text}\NormalTok{(}\AttributeTok{x=}\DecValTok{2}\NormalTok{, }\AttributeTok{y=}\FunctionTok{table}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{mois\_reussi, }\AttributeTok{useNA =} \StringTok{"no"}\NormalTok{)[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(Data)}\SpecialCharTok{+}\FloatTok{0.05}\NormalTok{, }\AttributeTok{labels=}\FunctionTok{paste0}\NormalTok{(}\FunctionTok{round}\NormalTok{(}\FunctionTok{table}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{mois\_reussi, }\AttributeTok{useNA =} \StringTok{"no"}\NormalTok{)[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(Data)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\DecValTok{2}\NormalTok{), }\StringTok{"\%"}\NormalTok{))}
\FunctionTok{barplot}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{mean}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{chrono\_reussi, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)),}
        \AttributeTok{main=}\StringTok{"Distribution Chronodel"}\NormalTok{, }\AttributeTok{ylim=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{1.1}\NormalTok{), }\AttributeTok{col=}\FunctionTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{, }\StringTok{"green"}\NormalTok{), }\AttributeTok{names.arg =} \FunctionTok{c}\NormalTok{(}\StringTok{"0"}\NormalTok{, }\StringTok{"1"}\NormalTok{))}
\FunctionTok{text}\NormalTok{(}\AttributeTok{x=}\DecValTok{1}\NormalTok{, }\AttributeTok{y=}\FloatTok{0.05}\NormalTok{, }\AttributeTok{labels=}\StringTok{"0\%"}\NormalTok{)}
\FunctionTok{text}\NormalTok{(}\AttributeTok{x=}\DecValTok{2}\NormalTok{, }\AttributeTok{y=}\FunctionTok{mean}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{chrono\_reussi, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}\SpecialCharTok{+}\FloatTok{0.05}\NormalTok{, }\AttributeTok{labels=}\FunctionTok{paste0}\NormalTok{(}\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(Data}\SpecialCharTok{$}\NormalTok{chrono\_reussi, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\DecValTok{2}\NormalTok{), }\StringTok{"\%"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Stats-Chronodel-Rstudio_files/Stats-Chronodel-Rstudio_files/figure-latex/unnamed-chunk-6-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

The distribution of the results for the \emph{DOTWB} test is really
unbalanced, with a majority of successful outcomes, which suggest
\textbf{clearly} a ceiling effect. The distribution of the results for
the \emph{MOTYB} test is more balanced, with 40\% of ``no'' and 57.5\%
of ``yes'', which doesn't suggest a ceiling effect. The distribution of
the results for the \emph{Chronodel} test is really unbalanced, with all
the subjects having a successful outcome, which \textbf{strongly suggest
a ceiling effect}. This ceiling effect can be explained by the fact that
the tests are not challenging enough for the subjects, and that the
subjects are able to perform the task without any difficulty, which is
not what we expected, and that is why we have low variability in the
results, and a high success rate for the three tests.

\end{document}
